<?php

require_once('zoo.inc');
require_once('include/util.inc');

 
$to_fetch = array(
 array("Ptarmigan","Lagopus","muta"),
 array("Red Grouse","Lagopus","lagopus"),
 array("Red-legged Partridge","Alectoris","rufa"),
 array("Grey Partridge","Perdix","perdix"),
 array("Quail","Coturnix","coturnix"),
 array("Pheasant","Phasianus","colchicus"),
 array("Brent Goose","Branta","bernicla"),
 array("Canada Goose","Branta","canadensis"),
 array("Barnacle Goose","Branta","leucopsis"),
 array("Greylag Goose","Anser","anser"),
 array("Pink-footed Goose","Anser","brachyrhynchus"),
 array("White-fronted Goose","Anser","albifrons"),
 array("Mute Swan","Cygnus","olor"),
 array("Bewick's Swan","Cygnus","columbianus"),
 array("Whooper Swan","Cygnus","cygnus"),
 array("Egyptian Goose","Alopochen","aegyptiaca"),
 array("Shelduck","Tadorna","tadorna"),
 array("Mandarin Duck","Aix","galericulata"),
 array("Gadwall","Mareca","strepera"),
 array("Wigeon","Mareca","penelope"),
 array("Mallard","Anas","platyrhynchos"),
 array("Pintail","Anas","acuta"),
 array("Teal","Anas","crecca"),
 array("Pochard","Aythya","ferina"),
 array("Tufted Duck","Aythya","fuligula"),
 array("Scaup","Aythya","marila"),
 array("Eider","Somateria","mollissima"),
 array("Velvet Scoter","Melanitta","fusca"),
 array("Common Scoter","Melanitta","nigra"),
 array("Long-tailed Duck","Clangula","hyemalis"),
 array("Goosander","Mergus","merganser"),
 array("Red-breasted Merganser","Mergus","serrator"),
 array("Nightjar","Caprimulgus","europaeus"),
 array("Swift","Apus","apus"),
 array("Cuckoo","Cuculus","canorus"),
 array("Rock Dove","Columba","livia"),
 array("Stock Dove","Columba","oenas"),
 array("Woodpigeon","Columba","palumbus"),
 array("Turtle Dove","Streptopelia","turtur"),
 array("Collared Dove","Streptopelia","decaocto"),
 array("Water Rail","Rallus","aquaticus"),
 array("Corncrake","Crex","crex"),
 array("Moorhen","Gallinula","chloropus"),
 array("Coot","Fulica","atra"),
 array("Little Grebe","Tachybaptus","ruficollis"),
 array("Great Crested Grebe","Podiceps","cristatus"),
 array("Oystercatcher","Haematopus","ostralegus"),
 array("Avocet","Recurvirostra","avosetta"),
 array("Lapwing","Vanellus","vanellus"),
 array("Golden Plover","Pluvialis","apricaria"),
 array("Grey Plover","Pluvialis","squatarola"),
 array("Ringed Plover","Charadrius","hiaticula"),
 array("Little Ringed Plover","Charadrius","dubius"),
 array("Dotterel","Charadrius","morinellus"),
 array("Whimbrel","Numenius","phaeopus"),
 array("Curlew","Numenius","arquata"),
 array("Bar-tailed Godwit","Limosa","lapponica"),
 array("Turnstone","Arenaria","interpres"),
 array("Knot","Calidris","canutus"),
 array("Sanderling","Calidris","alba"),
 array("Dunlin","Calidris","alpina"),
 array("Purple Sandpiper","Calidris","maritima"),
 array("Woodcock","Scolopax","rusticola"),
 array("Jack Snipe","Lymnocryptes","minimus"),
 array("Snipe","Gallinago","gallinago"),
 array("Common Sandpiper","Actitis","hypoleucos"),
 array("Redshank","Tringa","totanus"),
 array("Greenshank","Tringa","nebularia"),
 array("Kittiwake","Rissa","tridactyla"),
 array("Black-headed Gull","Chroicocephalus","ridibundus"),
 array("Common Gull","Larus","canus"),
 array("Great Black-backed Gull","Larus","marinus"),
 array("Herring Gull","Larus","argentatus"),
 array("Lesser Black-backed Gull","Larus","fuscus"),
 array("Sandwich Tern","Thalasseus","sandvicensis"),
 array("Little Tern","Sternula","albifrons"),
 array("Common Tern","Sterna","hirundo"),
 array("Arctic Tern","Sterna","paradisaea"),
 array("Great Skua","Stercorarius","skua"),
 array("Arctic Skua","Stercorarius","parasiticus"),
 array("Guillemot","Uria","aalge"),
 array("Razorbill","Alca","torda"),
 array("Black Guillemot","Cepphus","grylle"),
 array("Puffin","Fratercula","arctica"),
 array("Red-throated Diver","Gavia","stellata"),
 array("Great Northern Diver","Gavia","immer"),
 array("Storm Petrel","Hydrobates","pelagicus"),
 array("Leach's Petrel","Oceanodroma","leucorhoa"),
 array("Fulmar","Fulmarus","glacialis"),
 array("Manx Shearwater","Puffinus","puffinus"),
 array("Balearic Shearwater","Puffinus","mauretanicus"),
 array("Gannet","Morus","bassanus"),
 array("Shag","Phalacrocorax","aristotelis"),
 array("Cormorant","Phalacrocorax","carbo"),
 array("Grey Heron","Ardea","cinerea"),
 array("Osprey","Pandion","haliaetus"),
 array("Honey-buzzard","Pernis","apivorus"),
 array("Golden Eagle","Aquila","chrysaetos"),
 array("Sparrowhawk","Accipiter","nisus"),
 array("Marsh Harrier","Circus","aeruginosus"),
 array("Hen Harrier","Circus","cyaneus"),
 array("Red Kite","Milvus","milvus"),
 array("Buzzard","Buteo","buteo"),
 array("Barn Owl","Tyto","alba"),
 array("Tawny Owl","Strix","aluco"),
 array("Little Owl","Athene","noctua"),
 array("Long-eared Owl","Asio","otus"),
 array("Short-eared Owl","Asio","flammeus"),
 array("Kingfisher","Alcedo","atthis"),
 array("Lesser Spotted Woodpecker","Dryobates","minor"),
 array("Great Spotted Woodpecker","Dendrocopos","major"),
 array("Green Woodpecker","Picus","viridis"),
 array("Kestrel","Falco","tinnunculus"),
 array("Merlin","Falco","columbarius"),
 array("Hobby","Falco","subbuteo"),
 array("Peregrine","Falco","peregrinus"),
 array("Ring-necked Parakeet","Psittacula","krameri"),
 array("Jay","Garrulus","glandarius"),
 array("Magpie","Pica","pica"),
 array("Jackdaw","Coloeus","monedula"),
 array("Rook","Corvus","frugilegus"),
 array("Carrion Crow","Corvus","corone"),
 array("Hooded Crow","Corvus","cornix"),
 array("Raven","Corvus","corax"),
 array("Waxwing","Bombycilla","garrulus"),
 array("Coal Tit","Periparus","ater"),
 array("Crested Tit","Lophophanes","cristatus"),
 array("Marsh Tit","Poecile","palustris"),
 array("Willow Tit","Poecile","montanus"),
 array("Blue Tit","Cyanistes","caeruleus"),
 array("Great Tit","Parus","major"),
 array("Bearded Tit","Panurus","biarmicus"),
 array("Woodlark","Lullula","arborea"),
 array("Skylark","Alauda","arvensis"),
 array("Sand Martin","Riparia","riparia"),
 array("Swallow","Hirundo","rustica"),
 array("House Martin","Delichon","urbicum"),
 array("Cetti's Warbler","Cettia","cetti"),
 array("Long-tailed Tit","Aegithalos","caudatus"),
 array("Wood Warbler","Phylloscopus","sibilatrix"),
 array("Yellow-browed Warbler","Phylloscopus","inornatus"),
 array("Willow Warbler","Phylloscopus","trochilus"),
 array("Chiffchaff","Phylloscopus","collybita"),
 array("Sedge Warbler","Acrocephalus","schoenobaenus"),
 array("Reed Warbler","Acrocephalus","scirpaceus"),
 array("Grasshopper Warbler","Locustella","naevia"),
 array("Blackcap","Sylvia","atricapilla"),
 array("Garden Warbler","Sylvia","borin"),
 array("Lesser Whitethroat","Sylvia","curruca"),
 array("Whitethroat","Sylvia","communis"),
 array("Dartford Warbler","Sylvia","undata"),
 array("Firecrest","Regulus","ignicapilla"),
 array("Goldcrest","Regulus","regulus"),
 array("Wren","Troglodytes","troglodytes"),
 array("Nuthatch","Sitta","europaea"),
 array("Treecreeper","Certhia","familiaris"),
 array("Starling","Sturnus","vulgaris"),
 array("Ring Ouzel","Turdus","torquatus"),
 array("Blackbird","Turdus","merula"),
 array("Fieldfare","Turdus","pilaris"),
 array("Redwing","Turdus","iliacus"),
 array("Song Thrush","Turdus","philomelos"),
 array("Mistle Thrush","Turdus","viscivorus"),
 array("Spotted Flycatcher","Muscicapa","striata"),
 array("Robin","Erithacus","rubecula"),
 array("Nightingale","Luscinia","megarhynchos"),
 array("Pied Flycatcher","Ficedula","hypoleuca"),
 array("Redstart","Phoenicurus","phoenicurus"),
 array("Whinchat","Saxicola","rubetra"),
 array("Stonechat","Saxicola","rubicola"),
 array("Wheatear","Oenanthe","oenanthe"),
 array("Dipper","Cinclus","cinclus"),
 array("House Sparrow","Passer","domesticus"),
 array("Tree Sparrow","Passer","montanus"),
 array("Dunnock","Prunella","modularis"),
 array("Yellow Wagtail","Motacilla","flava"),
 array("Grey Wagtail","Motacilla","cinerea"),
 array("Pied Wagtail","Motacilla","alba"),
 array("Meadow Pipit","Anthus","pratensis"),
 array("Tree Pipit","Anthus","trivialis"),
 array("Rock Pipit","Anthus","petrosus"),
 array("Chaffinch","Fringilla","coelebs"),
 array("Brambling","Fringilla","montifringilla"),
 array("Hawfinch","Coccothraustes","coccothraustes"),
 array("Bullfinch","Pyrrhula","pyrrhula"),
 array("Greenfinch","Chloris","chloris"),
 array("Twite","Linaria","flavirostris"),
 array("Linnet","Linaria","cannabina"),
 array("Lesser Redpoll","Acanthis","cabaret"),
 array("Parrot Crossbill","Loxia","pytyopsittacus"),
 array("Scottish Crossbill","Loxia","scotica"),
 array("Common Crossbill","Loxia","curvirostra"),
 array("Goldfinch","Carduelis","carduelis"),
 array("Siskin","Spinus","spinus"),
 array("Lapland Bunting","Calcarius","lapponicus"),
 array("Corn Bunting","Emberiza","calandra"),
 array("Yellowhammer","Emberiza","citrinella"),
 array("Cirl Bunting","Emberiza","cirlus"),
 array("Reed Bunting","Emberiza","schoeniclus")
);

foreach($to_fetch as $x) {
 echo "Fetching {$x[0]} ({$x[1]} {$x[2]})<br/>\r\n";
 $html = fetch_wiki($x[1],$x[2]);

 $ss = $zoo->load_where('species',"x.species='{$x[2]}' AND x.genus='{$x[1]}'");

 if (! $ss) {
  $s = $zoo->new_object('species');
  $s->common_name = $x[0];
  $s->species = $x[2];
  $s->genus = $x[1];
  $t = extract_wiki_taxa($html);
  $s->family = $t->family;
  $s->order  = $t->order;
  $s->class  = $t->class;
  $s->save();
 }
}
